---
# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - 'v*'
  workflow_call:
    inputs:
      url:
        description: 'Forgejo instance URL'
        type: string
        required: false
        default: 'https://git.zyria.de'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Upload release assets
        uses: https://git.zyria.de/pyrox/actions/forgejo-release@a269dd68a82414587c9c81a4ae9a015c60dc2154 # v1
        with:
          url: ${{ inputs.url }}
          token: ${{ secrets.ZYRIA_TOKEN }}
