---

name: Pre-Commit Checks

on:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: https://code.forgejo.org/actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
      - name: Install detect-secret
        run: pip install detect-secrets
      - uses: https://github.com/pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
